name=YFPS2UARTLib
version=0.0.1
author=YFROBOT
maintainer=YFROBOT-ZL,<yfrobot@qq.com>
sentence=Library for YFROBOT PS2UART Module, interfacing with PS2 controllers via UART.
paragraph=This library provides an easy way to read button states and send vibration commands for PS2 controllers using UART communication. It includes methods for initializing the library, reading data, and processing button states.
category=Communication
url=https://github.com/YFROBOT-TM/Yfrobot-PS2UART-Library
architectures=arduino
includes=YFPS2UART.h